package com.localhost8888.enums;

public enum ConfigProperties {
  URL,
  OVERRIDEREPORTS,
  PASSEDSTEPSSCREENSHOTS,
  FAILEDSTEPSSCREENSHOTS,
  RETRYFAILEDTESTS,
  RUNMODE,
  SENDRESULTTOELK,
  SELENIUMGRIDURL,
  ELASTICURL,
  BROWSER
}
